name: Build Binaries

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build Windows executable
        run: |
          pyinstaller --noconsole --onefile --icon=icon.ico --add-data "icon.ico;." --copy-metadata pylast lyrics.pyw

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/*


  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Universal macOS binary
        run: |
          pyinstaller --noconsole --onefile --target-arch universal2 --add-data "icon.ico:." --copy-metadata pylast lyrics.pyw

      - name: Zip mac binary
        run: |
          cd dist
          zip Lyrics-for-Audirvana-mac.zip lyrics

      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/Lyrics-for-Audirvana-mac.zip
